### ISSUE TITLE
0.E Mutation missing values

### ISSUE THREAD

**Issue by Soyweiser** [Soyweiser/CDDA-Wiki-Scripts#26]
Some new values were added and some things were changed, this is a list of things I still need to fix. (these are ones actually used by mutations, the system supports a few more values which aren't used yet, which I have not added).
- [x] reading_speed_multiplier
- [x] movecost_modifier
- [x] movecost_flatground_modifier
- [x] movecost_swim_modifier
- [x] movecost_obstacle_modifier
- [x] speed_modifier
- [x] temperature_speed_modifier
- [x] attackcost_modifier
- [x] description now optionally has a "str" field.
- [x] player_display
- [x] name : str value added.
- [x] initial_ma_styles
- [x] max_stamina_modifier
- [x] mending_modifier
- [x] bash_dmg_bonus
- [x] cut_dmg_bonus
- [x] rand_cut_bonus
- [x] dodge_modifier
- [x] mixed_effect
- [x] wet_protection: neutral, good values added, need to check what the difference is between those and ignored. (added to the wet wiki page.)
- [x] weight_capacity_modifier
- [x] ranged_mutation
- [x] skill_rust_multiplier
- [x] noise_modifier
- [x] hearing_modifier
- [x] overmap_sight
- [x] map_memory_capacity_multiplier
- [x] vitamins_absorb_multi
- [x] vitamin_rates
- [x] scent_intensity
- [x] scent_type
- [x] lumination
- [x] flags (some descriptions missing from JSON_FLAGS.md)
- [x] craft_skill_bonus

**Comment by Fris0uman** [comment]
Relevant doc is there https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#traits-mutations might have a good chunk of the required infos

**Comment by Soyweiser** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_FLAGS.md#mutations
